<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
  /**
  * Run the database seeds.
  *
  * @return void
  */
  public function run()
  {
    DB::statement("INSERT INTO public.cities VALUES (2, 'SAN FERNANDO DE ATABAPO', 2, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (3, 'PUERTO AYACUCHO', 2, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (4, 'LA ESMERALDA', 2, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (5, 'ISLA RATÓN', 2, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (6, 'MAROA', 2, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (7, 'SAN JUAN DE MANAPIARE', 2, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (8, 'SAN CARLOS DE RÍO NEGRO', 2, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (9, 'ANACO', 1, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (10, 'ARAGUA DE BARCELONA', 1, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (11, 'PUERTO PÍRITU', 1, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (12, 'VALLE DE GUANAPE', 1, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (13, 'PARIAGUÁN', 1, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (14, 'GUANTA', 1, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (15, 'SOLEDAD', 1, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (17, 'ONOTO', 1, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (18, 'MAPIRE', 1, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (19, 'SAN MATEO', 1, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (20, 'CLARINES', 1, true, false, '12')");
    DB::statement("INSERT INTO public.cities VALUES (21, 'CANTAURA', 1, true, false, '13')");
    DB::statement("INSERT INTO public.cities VALUES (22, 'PÍRITU', 1, true, false, '14')");
    DB::statement("INSERT INTO public.cities VALUES (23, 'SAN JOSÉ DE GUANIPA (EL TIGRITO)', 1, true, false, '15')");
    DB::statement("INSERT INTO public.cities VALUES (24, 'BOCA DE UCHIRE', 1, true, false, '16')");
    DB::statement("INSERT INTO public.cities VALUES (37, 'SAN MATEO', 4, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (26, 'BARCELONA', 1, true, false, '18')");
    DB::statement("INSERT INTO public.cities VALUES (27, 'EL TIGRE', 1, true, false, '19')");
    DB::statement("INSERT INTO public.cities VALUES (28, 'EL CHAPARRO', 1, true, false, '20')");
    DB::statement("INSERT INTO public.cities VALUES (29, 'LECHERÍAS', 1, true, false, '21')");
    DB::statement("INSERT INTO public.cities VALUES (31, 'BIRUACA', 3, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (32, 'BRUZUAL', 3, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (33, 'GUASDUALITO', 3, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (34, 'SAN JUAN DE PAYARA', 3, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (35, 'ELORZA', 3, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (36, 'SAN FERNANDO DE APURE', 3, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (25, 'SANTA ANA', 1, true, false, '17')");
    DB::statement("INSERT INTO public.cities VALUES (38, 'CAMATAGUA', 4, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (39, 'MARACAY', 4, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (40, 'SANTA CRUZ', 4, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (41, 'LA VICTORIA', 4, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (42, 'EL CONSEJO', 4, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (43, 'PALO NEGRO', 4, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (45, 'SAN CASIMIRO', 4, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (46, 'SAN SEBASTIÁN', 4, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (47, 'TURMERO', 4, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (48, 'LAS TEJERÍAS', 4, true, false, '12')");
    DB::statement("INSERT INTO public.cities VALUES (49, 'CAGUA', 4, true, false, '13')");
    DB::statement("INSERT INTO public.cities VALUES (50, 'LA COLONIA TOVAR', 4, true, false, '14')");
    DB::statement("INSERT INTO public.cities VALUES (51, 'BARBACOAS', 4, true, false, '15')");
    DB::statement("INSERT INTO public.cities VALUES (52, 'VILLA DE CURA', 4, true, false, '16')");
    DB::statement("INSERT INTO public.cities VALUES (53, 'SANTA RITA', 4, true, false, '17')");
    DB::statement("INSERT INTO public.cities VALUES (54, 'OCUMARE DE LA COSTA', 4, true, false, '18')");
    DB::statement("INSERT INTO public.cities VALUES (55, 'SABANETA', 5, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (56, 'SOCOPÓ', 5, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (57, 'ARISMENDI', 5, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (58, 'BARINAS', 5, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (60, 'BARRANCAS', 5, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (61, 'SANTA BÁRBARA', 5, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (62, 'OBISPOS', 5, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (63, 'CIUDAD BOLIVIA', 5, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (64, 'LIBERTAD', 5, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (65, 'CIUDAD DE NUTRIAS', 5, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (66, 'EL CANTÓN', 5, true, false, '12')");
    DB::statement("INSERT INTO public.cities VALUES (67, 'CIUDAD GUAYANA', 16, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (68, 'CIUDAD BOLÍVAR', 16, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (69, 'CAICARA DEL ORINOCO', 16, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (70, 'EL CALLAO', 16, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (72, 'UPATA', 16, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (73, 'CIUDAD PIAR', 16, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (74, 'GUASIPATI', 16, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (75, 'TUMEREMO', 16, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (76, 'MARIPA', 16, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (77, 'EL PALMAR', 16, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (79, 'GÜIGÜE', 17, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (78, 'BEJUMA', 17, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (80, 'MARIARA', 17, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (81, 'GUACARA', 17, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (82, 'MORÓN', 17, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (83, 'TOCUYITO', 17, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (84, 'LOS GUAYOS', 17, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (85, 'MIRANDA', 17, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (86, 'MONTALBÁN', 17, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (87, 'NAGUANAGUA', 17, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (89, 'SAN DIEGO', 17, true, false, '12')");
    DB::statement("INSERT INTO public.cities VALUES (90, 'SAN JOAQUÍN', 17, true, false, '13')");
    DB::statement("INSERT INTO public.cities VALUES (91, 'VALENCIA', 17, true, false, '14')");
    DB::statement("INSERT INTO public.cities VALUES (92, 'COJEDES', 18, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (93, 'TINAQUILLO', 18, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (94, 'EL BAÚL', 18, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (95, 'MACAPO', 18, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (96, 'EL PAO', 18, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (97, 'LIBERTAD', 18, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (98, 'LAS VEGAS', 18, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (99, 'SAN CARLOS', 18, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (100, 'TINACO', 18, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (101, 'CURIAPO', 19, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (102, 'SIERRA IMATACA', 19, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (103, 'PEDERNALES', 19, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (105, 'SAN JUAN DE LOS CAYOS', 7, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (106, 'SAN LUIS', 7, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (107, 'CAPATÁRIDA', 7, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (108, 'YARACAL', 7, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (109, 'PUNTO FIJO', 7, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (110, 'LA VELA DE CORO', 7, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (111, 'DABAJURO', 7, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (112, 'PEDREGAL', 7, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (113, 'PUEBLO NUEVO', 7, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (114, 'CHURUGUARA', 7, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (115, 'JACURA', 7, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (117, 'MENE DE MAUROA', 7, true, false, '13')");
    DB::statement("INSERT INTO public.cities VALUES (118, 'SANTA ANA DE CORO', 7, true, false, '14')");
    DB::statement("INSERT INTO public.cities VALUES (119, 'CHICHIRIVICHE', 7, true, false, '15')");
    DB::statement("INSERT INTO public.cities VALUES (120, 'PALMASOLA', 7, true, false, '16')");
    DB::statement("INSERT INTO public.cities VALUES (121, 'CABURE', 7, true, false, '17')");
    DB::statement("INSERT INTO public.cities VALUES (122, 'PÍRITU', 7, true, false, '18')");
    DB::statement("INSERT INTO public.cities VALUES (123, 'MIRIMIRE', 7, true, false, '19')");
    DB::statement("INSERT INTO public.cities VALUES (124, 'TUCACAS', 7, true, false, '20')");
    DB::statement("INSERT INTO public.cities VALUES (125, 'LA CRUZ DE TARATARA', 7, true, false, '21')");
    DB::statement("INSERT INTO public.cities VALUES (126, 'TOCÓPERO', 7, true, false, '22')");
    DB::statement("INSERT INTO public.cities VALUES (127, 'SANTA CRUZ DE BUCARAL', 7, true, false, '23')");
    DB::statement("INSERT INTO public.cities VALUES (128, 'URUMACO', 7, true, false, '24')");
    DB::statement("INSERT INTO public.cities VALUES (129, 'PUERTO CUMAREBO', 7, true, false, '25')");
    DB::statement("INSERT INTO public.cities VALUES (130, 'CAMAGUÁN', 8, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (131, 'CHAGUARAMAS', 8, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (132, 'EL SOCORRO', 8, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (133, 'GUAYABAL', 8, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (135, 'LAS MERCEDES', 8, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (136, 'EL SOMBRERO', 8, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (137, 'CALABOZO', 8, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (138, 'ALTAGRACIA DE ORITUCO', 8, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (139, 'ORTIZ', 8, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (140, 'TUCUPIDO', 8, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (141, 'SAN JUAN DE LOS MORROS', 8, true, false, '12')");
    DB::statement("INSERT INTO public.cities VALUES (142, 'SAN JOSÉ DE GUARIBE', 8, true, false, '13')");
    DB::statement("INSERT INTO public.cities VALUES (236, 'CASANAY', 19, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (237, 'SAN JOSÉ DE AEROCUAR', 19, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (144, 'ZARAZA', 8, true, false, '15')");
    DB::statement("INSERT INTO public.cities VALUES (145, 'SANARE', 9, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (146, 'DUACA', 9, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (147, 'BARQUISIMETO', 9, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (148, 'QUÍBOR', 9, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (149, 'EL TOCUYO', 9, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (150, 'CABUDARE', 9, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (151, 'SARARE', 9, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (152, 'CARORA', 9, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (154, 'EL VIGÍA', 10, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (155, 'LA AZULITA', 10, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (156, 'SANTA CRUZ DE MORA', 10, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (157, 'ARICAGUA', 10, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (158, 'CANAGUÁ', 10, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (159, 'EJIDO', 10, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (160, 'TUCANÍ', 10, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (161, 'SANTO DOMINGO', 10, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (162, 'GUARAQUE', 10, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (163, 'ARAPUEY', 10, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (164, 'TORONDOY', 10, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (165, 'MÉRIDA', 10, true, false, '12')");
    DB::statement("INSERT INTO public.cities VALUES (166, 'TIMOTES', 10, true, false, '13')");
    DB::statement("INSERT INTO public.cities VALUES (168, 'SANTA MARÍA DE CAPARO', 10, true, false, '15')");
    DB::statement("INSERT INTO public.cities VALUES (169, 'PUEBLO LLANO', 10, true, false, '16')");
    DB::statement("INSERT INTO public.cities VALUES (170, 'MUCUCHÍES', 10, true, false, '17')");
    DB::statement("INSERT INTO public.cities VALUES (171, 'BAILADORES', 10, true, false, '18')");
    DB::statement("INSERT INTO public.cities VALUES (172, 'TABAY', 10, true, false, '19')");
    DB::statement("INSERT INTO public.cities VALUES (173, 'LAGUNILLAS', 10, true, false, '20')");
    DB::statement("INSERT INTO public.cities VALUES (174, 'TOVAR', 10, true, false, '21')");
    DB::statement("INSERT INTO public.cities VALUES (175, 'NUEVA BOLIVIA', 10, true, false, '22')");
    DB::statement("INSERT INTO public.cities VALUES (176, 'ZEA', 10, true, false, '23')");
    DB::statement("INSERT INTO public.cities VALUES (197, 'GUATIRE', 11, true, false, '21')");
    DB::statement("INSERT INTO public.cities VALUES (196, 'CÚA', 11, true, false, '20')");
    DB::statement("INSERT INTO public.cities VALUES (194, 'SAN FRANCISCO DE YARE', 11, true, false, '18')");
    DB::statement("INSERT INTO public.cities VALUES (193, 'GUARENAS', 11, true, false, '17')");
    DB::statement("INSERT INTO public.cities VALUES (192, 'CÚPIRA', 11, true, false, '16')");
    DB::statement("INSERT INTO public.cities VALUES (191, 'SANTA LUCÍA', 11, true, false, '15')");
    DB::statement("INSERT INTO public.cities VALUES (190, 'RÍO CHICO', 11, true, false, '14')");
    DB::statement("INSERT INTO public.cities VALUES (188, 'OCUMARE DEL TUY', 11, true, false, '12')");
    DB::statement("INSERT INTO public.cities VALUES (187, 'SANTA TERESA DEL TUY', 11, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (186, 'LOS TEQUES', 11, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (184, 'CHARALLAVE', 11, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (182, 'CARRIZAL', 11, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (181, 'MAMPORAL', 11, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (180, 'HIGUEROTE', 11, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (198, 'SAN ANTONIO', 20, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (199, 'AGUASAY', 20, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (200, 'CARIPITO', 20, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (202, 'CAICARA', 20, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (201, 'CARIPE', 20, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (203, 'PUNTA DE MATA', 20, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (204, 'TEMBLADOR', 20, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (205, 'MATURÍN', 20, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (206, 'ARAGUA', 20, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (207, 'QUIRIQUIRE', 20, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (209, 'BARRANCAS', 20, true, false, '12')");
    DB::statement("INSERT INTO public.cities VALUES (210, 'URACOA', 20, true, false, '13')");
    DB::statement("INSERT INTO public.cities VALUES (221, 'SAN PEDRO DE COCHE', 21, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (220, 'PUNTA DE PIEDRAS', 21, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (219, 'BOCA DEL RÍO', 21, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (218, 'PORLAMAR', 21, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (217, 'JUANGRIEGO', 21, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (216, 'PAMPATAR', 21, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (215, 'SANTA ANA', 21, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (213, 'SAN JUAN BAUTISTA', 21, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (212, 'LA ASUNCIÓN', 21, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (234, 'BISCUCUY', 12, true, false, '13')");
    DB::statement("INSERT INTO public.cities VALUES (211, 'PLAZA PARAGUACHÍ', 21, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (235, 'VILLA BRUZUAL', 12, true, false, '14')");
    DB::statement("INSERT INTO public.cities VALUES (233, 'EL PLAYÓN', 12, true, false, '12')");
    DB::statement("INSERT INTO public.cities VALUES (232, 'SAN RAFAEL DE ONOTO', 12, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (231, 'BOCONOITO', 12, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (230, 'PAPELÓN', 12, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (229, 'ACARIGUA', 12, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (228, 'OSPINO', 12, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (227, 'PARAÍSO DE CHABASQUÉN', 12, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (226, 'GUANARITO', 12, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (225, 'GUANARE', 12, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (224, 'PÍRITU', 12, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (223, 'ARAURE', 12, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (222, 'AGUA BLANCA', 12, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (250, 'GÜIRIA', 22, true, false, '15')");
    DB::statement("INSERT INTO public.cities VALUES (249, 'CUMANÁ', 22, true, false, '14')");
    DB::statement("INSERT INTO public.cities VALUES (248, 'CARIACO', 22, true, false, '13')");
    DB::statement("INSERT INTO public.cities VALUES (247, 'CUMANACOA', 22, true, false, '12')");
    DB::statement("INSERT INTO public.cities VALUES (245, 'IRAPA', 22, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (244, 'TUNAPUY', 22, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (243, 'ARAYA', 22, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (242, 'YAGUARAPARO', 22, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (241, 'MARIGÜITAR', 22, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (240, 'CARÚPANO', 22, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (239, 'EL PILAR', 22, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (238, 'RÍO CARIBE', 22, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (279, 'UMUQUENA', 13, true, false, '29')");
    DB::statement("INSERT INTO public.cities VALUES (278, 'PREGONERO', 13, true, false, '28')");
    DB::statement("INSERT INTO public.cities VALUES (276, 'QUENIQUEA', 13, true, false, '26')");
    DB::statement("INSERT INTO public.cities VALUES (277, 'SAN JOSECITO', 13, true, false, '27')");
    DB::statement("INSERT INTO public.cities VALUES (275, 'SAN SIMÓN', 13, true, false, '25')");
    DB::statement("INSERT INTO public.cities VALUES (274, 'SEBORUCO', 13, true, false, '24')");
    DB::statement("INSERT INTO public.cities VALUES (273, 'SAN CRISTÓBAL', 13, true, false, '23')");
    DB::statement("INSERT INTO public.cities VALUES (272, 'LA TENDIDA', 13, true, false, '22')");
    DB::statement("INSERT INTO public.cities VALUES (271, 'DELICIAS', 13, true, false, '21')");
    DB::statement("INSERT INTO public.cities VALUES (270, 'UREÑA', 13, true, false, '20')");
    DB::statement("INSERT INTO public.cities VALUES (268, 'MICHELENA', 13, true, false, '18')");
    DB::statement("INSERT INTO public.cities VALUES (267, 'LOBATERA', 13, true, false, '17')");
    DB::statement("INSERT INTO public.cities VALUES (266, 'ABEJALES', 13, true, false, '16')");
    DB::statement("INSERT INTO public.cities VALUES (265, 'CAPACHO VIEJO', 13, true, false, '15')");
    DB::statement("INSERT INTO public.cities VALUES (264, 'RUBIO', 13, true, false, '14')");
    DB::statement("INSERT INTO public.cities VALUES (263, 'EL COBRE', 13, true, false, '13')");
    DB::statement("INSERT INTO public.cities VALUES (262, 'LA GRITA', 13, true, false, '12')");
    DB::statement("INSERT INTO public.cities VALUES (261, 'CAPACHO NUEVO', 13, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (260, 'PALMIRA', 13, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (259, 'LA FRÍA', 13, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (257, 'SAN RAFAEL DEL PIÑAL', 13, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (256, 'SANTA ANA', 13, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (255, 'TÁRIBA', 13, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (254, 'SAN ANTONIO DEL TÁCHIRA', 13, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (253, 'COLÓN', 13, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (252, 'LAS MESAS', 13, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (251, 'CORDERO', 13, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (289, 'PAMPÁN', 14, true, false, '13')");
    DB::statement("INSERT INTO public.cities VALUES (288, 'EL DIVIDIVE', 14, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (287, 'MOTATÁN', 14, true, false, '12')");
    DB::statement("INSERT INTO public.cities VALUES (286, 'MONTE CARMELO', 14, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (285, 'SANTA APOLONIA', 14, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (284, 'CAMPO ELÍAS', 14, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (283, 'CARACHE', 14, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (282, 'EL PARADERO', 14, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (281, 'ESCUQUE', 14, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (280, 'SANTA ISABEL', 14, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (1, 'CARACAS', 6, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (16, 'PUERTO LA CRUZ', 1, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (30, 'ACHAGUAS', 3, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (44, 'EL LIMÓN', 4, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (59, 'BARINITAS', 5, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (71, 'SANTA ELENA DE UAIRÉN', 16, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (88, 'PUERTO CABELLO', 17, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (104, 'TUCUPITA', 19, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (116, 'SANTA CRUZ DE LOS TAQUES', 7, true, false, '12')");
    DB::statement("INSERT INTO public.cities VALUES (134, 'VALLE DE LA PASCUA', 8, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (143, 'SANTA MARÍA DE IPIRE', 8, true, false, '14')");
    DB::statement("INSERT INTO public.cities VALUES (153, 'SIQUISIQUE', 9, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (167, 'SANTA ELENA DE ARENALES', 10, true, false, '14')");
    DB::statement("INSERT INTO public.cities VALUES (195, 'PETARE', 11, true, false, '19')");
    DB::statement("INSERT INTO public.cities VALUES (189, 'SAN ANTONIO DE LOS ALTOS', 11, true, false, '13')");
    DB::statement("INSERT INTO public.cities VALUES (185, 'EL HATILLO', 11, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (183, 'CHACAO', 11, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (208, 'SANTA BÁRBARA', 20, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (214, 'EL VALLE DEL ESPÍRITU SANTO', 21, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (246, 'SAN ANTONIO DEL GOLFO', 22, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (269, 'COLONCITO', 13, true, false, '19')");
    DB::statement("INSERT INTO public.cities VALUES (258, 'SAN JOSÉ DE BOLÍVAR', 13, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (296, 'LA QUEBRADA', 14, true, false, '19')");
    DB::statement("INSERT INTO public.cities VALUES (295, 'VALERA', 14, true, false, '20')");
    DB::statement("INSERT INTO public.cities VALUES (294, 'TRUJILLO', 14, true, false, '18')");
    DB::statement("INSERT INTO public.cities VALUES (293, 'SABANA DE MENDOZA', 14, true, false, '17')");
    DB::statement("INSERT INTO public.cities VALUES (292, 'CARVAJAL', 14, true, false, '16')");
    DB::statement("INSERT INTO public.cities VALUES (291, 'BETIJOQUE', 14, true, false, '15')");
    DB::statement("INSERT INTO public.cities VALUES (290, 'PAMPANITO', 14, true, false, '14')");
    DB::statement("INSERT INTO public.cities VALUES (310, 'FARRIAR', 23, true, false, '14')");
    DB::statement("INSERT INTO public.cities VALUES (311, 'EL TORO', 24, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (309, 'URACHICHE', 23, true, false, '13')");
    DB::statement("INSERT INTO public.cities VALUES (308, 'GUAMA', 23, true, false, '12')");
    DB::statement("INSERT INTO public.cities VALUES (307, 'SAN FELIPE', 23, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (306, 'YARITAGUA', 23, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (305, 'NIRGUA', 23, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (304, 'YUMARE', 23, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (303, 'BORAURE', 23, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (302, 'SABANA DE PARRA', 23, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (301, 'INDEPENDENCIA', 23, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (300, 'COCOROTE', 23, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (299, 'CHIVACOA', 23, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (298, 'AROA', 23, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (297, 'SAN PABLO', 23, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (332, 'LA GUAIRA', 15, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (331, 'BACHAQUERO', 24, true, false, '21')");
    DB::statement("INSERT INTO public.cities VALUES (330, 'BOBURES', 24, true, false, '20')");
    DB::statement("INSERT INTO public.cities VALUES (329, 'TÍA JUANA', 24, true, false, '19')");
    DB::statement("INSERT INTO public.cities VALUES (328, 'SANTA RITA', 24, true, false, '18')");
    DB::statement("INSERT INTO public.cities VALUES (327, 'SAN FRANCISCO', 24, true, false, '17')");
    DB::statement("INSERT INTO public.cities VALUES (326, 'LA VILLA DEL ROSARIO', 24, true, false, '16')");
    DB::statement("INSERT INTO public.cities VALUES (325, 'SINAMAICA', 24, true, false, '15')");
    DB::statement("INSERT INTO public.cities VALUES (324, 'LOS PUERTOS DE ALTAGRACIA', 24, true, false, '14')");
    DB::statement("INSERT INTO public.cities VALUES (323, 'MARACAIBO', 24, true, false, '13')");
    DB::statement("INSERT INTO public.cities VALUES (322, 'SAN RAFAEL DE EL MOJÁN', 24, true, false, '12')");
    DB::statement("INSERT INTO public.cities VALUES (321, 'MACHIQUES', 24, true, false, '11')");
    DB::statement("INSERT INTO public.cities VALUES (320, 'CIUDAD  OJEDA', 24, true, false, '10')");
    DB::statement("INSERT INTO public.cities VALUES (319, 'CONCEPCIÓN', 24, true, false, '09')");
    DB::statement("INSERT INTO public.cities VALUES (318, 'CASIGUA (EL CUBO)', 24, true, false, '08')");
    DB::statement("INSERT INTO public.cities VALUES (317, 'LA CONCEPCIÓN', 24, true, false, '07')");
    DB::statement("INSERT INTO public.cities VALUES (316, 'PUEBLO NUEVO (EL CHIVO)', 24, true, false, '06')");
    DB::statement("INSERT INTO public.cities VALUES (315, 'SAN CARLOS DEL ZULIA', 24, true, false, '05')");
    DB::statement("INSERT INTO public.cities VALUES (314, 'ENCONTRADOS', 24, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (313, 'CABIMAS', 24, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (312, 'SAN TIMOTEO', 24, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (177, 'CAUCAGUA', 11, true, false, '01')");
    DB::statement("INSERT INTO public.cities VALUES (178, 'SAN JOSÉ DE BARLOVENTO', 11, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (179, 'NUESTRA SEÑORA DEL ROSARIO', 11, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (333, 'BOCONÓ', 14, true, false, '02')");
    DB::statement("INSERT INTO public.cities VALUES (335, 'CHEJENDÉ', 14, true, false, '04')");
    DB::statement("INSERT INTO public.cities VALUES (334, 'SABANA GRANDE', 14, true, false, '03')");
    DB::statement("INSERT INTO public.cities VALUES (999, 'Sin descripción', 99, true, false, '')");
    DB::statement(
        "UPDATE public.cities
            SET created_at = now()::timestamp(0) without time zone,
                updated_at = now()::timestamp(0) without time zone"
    );
  }
}
